version: "3"
services:
  rhine-cloud-driver:
    container_name: rhine-cloud-driver
    image: dreamxw/rhine-cloud-driver:latest
    restart: always
    volumes:
      - ./rhine-cloud-driver/uploads:/rhine-cloud-driver/uploads
      - ./rhine-cloud-driver/Rhine-Cloud-Driver.yaml:/rhine-cloud-driver/conf/Rhine-Cloud-Driver.yaml
      - ./rhine-cloud-driver/avatar:/rhine-cloud-driver/avatar
      - ./rhine-cloud-driver/logs:/rhine-cloud-driver/logs
    depends_on:
      - mysql
      - redis
      - nginx
    network_mode: host
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Test123456
      - MYSQL_DATABASE=project
    network_mode: host
  redis:
    container_name: redis
    image: redis:7.0
    restart: always
    network_mode: host
  nginx:
    container_name: nginx
    image: nginx:1.23.2
    restart: always
    network_mode: host
    volumes:
      - ./rhine-cloud-driver/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./rhine-cloud-driver/nginx/build:/usr/share/nginx/html
      - ./rhine-cloud-driver/nginx/cert:/etc/nginx/cert
    # 请执行：
    # mkdir -vp rhine-cloud-driver/{avatar,uploads} \
    # touch Rhine-Cloud-Driver.yaml