version: "3"
services:
  rhine-cloud-driver:
    container_name: rhine-cloud-driver
    image: dreamxw/rhine-cloud-driver:latest
    restart: always
    volumes:
      - ./uploads:/rhine-cloud-driver/uploads
      - ./config.yaml:/rhine-cloud-driver/config.yaml
      - ./avatar:/rhine-cloud-driver/avatar
      - ./logs:/rhine-cloud-driver/logs
    depends_on:
      - mysql
      - redis
      - nginx
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 600M
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Test123456
      - MYSQL_DATABASE=project
    network_mode: host
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
  redis:
    container_name: redis
    image: redis:7.0
    restart: always
    network_mode: host
  nginx:
    container_name: nginx
    image: nginx:1.23.2
    restart: always
    network_mode: host
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html
      - ./cert:/etc/nginx/cert
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 600M
    # 请执行：
    # mkdir -vp rhine-cloud-driver/{avatar,uploads} \
    # touch Rhine-Cloud-Driver.yaml