version: "3"
services:
  rhine-cloud-driver:
    container_name: rhine-cloud-driver
    image: dreamxw/rhine-cloud-driver:latest
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./rhine-cloud-driver/uploads:/rhine-cloud-driver/uploads
      - ./rhine-cloud-driver/Rhine-Cloud-Driver.yaml:/rhine-cloud-driver/conf/Rhine-Cloud-Driver.yaml
      - ./rhine-cloud-driver/avatar:/rhine-cloud-driver/avatar
      - ./rhine-cloud-driver/logs:/rhine-cloud-driver/logs
    depends_on:
      - mysql
      - redis
      - nginx
    networks:
      net:
        ipv4_address: 192.168.5.101
  mysql:
    container_name: mysql
    image: mysql:8.0.31
    restart: always
    ports:
      - "3306:3006"
    environment:
      - MYSQL_ROOT_PASSWORD=Test123456
      - MYSQL_DATABASE=project
    networks:
      net:
        ipv4_address: 192.168.5.102
  redis:
    container_name: redis
    image: redis:7.0
    ports:
      - "6379:6379"
    restart: always
    networks:
      net:
        ipv4_address: 192.168.5.103
  nginx:
    container_name: nginx
    image: nginx:1.23.2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      net:
        ipv4_address: 192.168.5.104
    volumes:
      - ./rhine-cloud-driver/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./rhine-cloud-driver/nginx/build:/usr/share/nginx/html

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.5.0/24
    # 请执行：
    # mkdir -vp rhine-cloud-driver/{avatar,uploads} \
    # touch Rhine-Cloud-Driver.yaml