version: "3"
services:
  rhine-cloud-driver:
    container_name: rhine-cloud-driver
    image: dreamxw/rhine-cloud-driver:latest
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./rhine-cloud-driver/uploads:/rhine-cloud-driver/uploads
      - ./rhine-cloud-driver/Rhine-Cloud-Driver.yaml:/rhine-cloud-driver/conf/Rhine-Cloud-Driver.yaml
      - ./rhine-cloud-driver/avatar:/rhine-cloud-driver/avatar
      - ./rhine-cloud-driver/logs:/rhine-cloud-driver/logs
    depends_on:
      - mysql
      - redis
      - nginx
  mysql:
    container_name: mysql
    image: mysql:8.0.31
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=your_mysql_password
      - MYSQL_TCP_PORT=3306
      - MYSQL_DATABASE=project
  redis:
    container_name: redis
    image: redis:7.0
    restart: always
  nginx:
    container_name: nginx
    image: nginx:1.23.2
    restart: always

    # 请执行：
    # mkdir -vp rhine-cloud-driver/{avatar,uploads} \
    # touch Rhine-Cloud-Driver.yaml